name: 'Pull request'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@feat/72-make-wip-opt-in
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
