name: 'Pull request'
on:
  # Running on push is necessary as a commit resets
  # all checks and so they need to run again.
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened
      - edited

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
