name: 'Pull request'
on:
  - push # Running on push is necessary as otherwise previously failed checks are omitted
  - pull_request:
    types:
      - opened
      - edited

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1.0.0
